/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause) */
/*
 * testcases.h
 *
 * Send feedback to <linux-can@vger.kernel.org>
 *
 */
#include <stdbool.h>
#include <linux/can.h>
#include <linux/can/isotp.h>

struct isotp_testcase {
	struct sockaddr_can addr;
	struct can_isotp_options opts;
	struct can_isotp_fc_options fcopts;
	struct can_isotp_ll_options llopts;
	struct can_isotp_xl_options xlopts;
};

struct isotp_testcase_description {
	unsigned mtu;
	unsigned tx_dl;
	unsigned blocksize;
	bool check_opt;
	bool check_pad;
	bool extaddr;
	bool brs;
	bool sec;
	bool rrs;
	bool vcid;
};

const struct isotp_testcase_description tcd [] = {
	{ /* CC 8 */
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
	},
	{
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
	},
	{
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.blocksize = 9,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
	},
	{
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
	},
	{
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
	},
	{
		.mtu = CAN_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
	},
	{ /* FD 8 */
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.brs = true,
	},
	{ /* FD 12 */
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.blocksize = 9,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 12,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.brs = true,
	},
	{ /* FD 16 */
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 16,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.brs = true,
	},
	{ /* FD 64 */
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.blocksize = 9,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
		.brs = true,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.brs = false,
	},
	{
		.mtu = CANFD_MTU,
		.tx_dl = 64,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.brs = true,
	},
	{ /* XL 8 */
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = false,
		.sec = true,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.blocksize = 9,
		.check_opt = true,
		.check_pad = true,
		.extaddr = false,
		.sec = false,
		.rrs = true,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.check_opt = false,
		.check_pad = false,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 8,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.sec = true,
		.rrs = false,
		.vcid = true,
	},
	{ /* XL 9 */
		.mtu = CANXL_MTU,
		.tx_dl = 9,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 9,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 9,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 9,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 16 */
		.mtu = CANXL_MTU,
		.tx_dl = 16,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 16,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 16,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 16,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 20 pad */
		.mtu = CANXL_MTU,
		.tx_dl = 20,
		.check_opt = false,
		.check_pad = false,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 20,
		.check_opt = true,
		.check_pad = false,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 20,
		.check_opt = false,
		.check_pad = true,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 20,
		.check_opt = true,
		.check_pad = true,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 64 */
		.mtu = CANXL_MTU,
		.tx_dl = 64,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 64,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 64,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 64,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 256 */
		.mtu = CANXL_MTU,
		.tx_dl = 256,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 256,
		.blocksize = 9,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 256,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 256,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 257 */
		.mtu = CANXL_MTU,
		.tx_dl = 257,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 257,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 257,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 257,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 2047 */
		.mtu = CANXL_MTU,
		.tx_dl = 2047,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2047,
		.blocksize = 9,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2047,
		.blocksize = 1,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2047,
		.blocksize = 2,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{ /* XL 2048 */
		.mtu = CANXL_MTU,
		.tx_dl = 2048,
		.extaddr = false,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2048,
		.extaddr = true,
		.sec = false,
		.rrs = false,
		.vcid = false,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2048,
		.extaddr = false,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
	{
		.mtu = CANXL_MTU,
		.tx_dl = 2048,
		.extaddr = true,
		.sec = true,
		.rrs = true,
		.vcid = true,
	},
};

#define MAXTCD (sizeof(tcd) / sizeof((tcd)[0]))

#define MAXTESTLEN 14

#define CRTL_CAN_ID 0x777

